####
## Sample docker compose file for running   ghcr.io/sujaykumarh/pocketbase   image
####

name: pocketbase

networks:
  net:

services:

  server:
    image: ghcr.io/sujaykumarh/pocketbase:${PB_VER:-latest}
    container_name: ${CONTAINER_NAME:-pb_server}
    restart: unless-stopped
    networks:
      - net
    security_opt:
      - no-new-privileges:true
    ports:
      - ${HTTP_PORT:-8080}:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ${DATA_DIR:-./data}/pb:/app/pb_data